name: "Home Management"
description: "Keep track of your household."
version: "0.0.4"
slug: "homemanage"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000